apiVersion: v1
kind: Service
metadata:
  name: sistema-noticias-service
  namespace: sistema-noticias-namespace
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: sistema-noticias-pod
