apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias-pod
  labels:
    app: sistema-noticias-pod
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
