apiVersion: v1
kind: ConfigMap
metadata:
  name: db-noticias-configmap
  namespace: sistema-noticias-namespace
data:
  MYSQL_ROOT_PASSWORD: q1w2e3r4
  MYSQL_DATABASE: empresa
  MYSQL_PASSWORD: q1w2e3r4
