apiVersion: v1
kind: Pod
metadata:
  name: db-noticias-pod
  namespace: sistema-noticias-namespace
  labels:
    app: db-noticias-pod
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom: 
        - configMapRef:
            name: db-noticias-configmap
