apiVersion: v1
kind: Pod
metadata:
  name: news-portal
  labels:
    name: news-portal
spec:
  containers:
  - name: news-portal
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8056
